@baseUrl = https://localhost:3000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZWRhMjIwZjE1NzdhYTlhMzE0YWIzMCIsImlhdCI6MTcyOTUyMDU3NCwiZXhwIjoxNzUxMTIwNTc0fQ.lIgTInBGJjGRJXhRn1TMfQmGoDBhtLay-Vu-zlUw57Y

### Test API

#### Get all tests
GET {{baseUrl}}/test
Authorization: Bearer {{accessToken}}   



### add a test
POST {{baseUrl}}/test
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "IELTS General Training Practice Test",
  "description": "A comprehensive practice test for IELTS General Training, covering all four sections.",
  "duration": 20,
  "sections": [
    {
      "name": "reading",
      "sectionScore": 18,
      "instruction": "Read three passages and answer questions to demonstrate your understanding.",
      "duration": 5,
      "passages": [
        { "_id": "67177ef52774d386da36ec59", "points": 12 },
        { "_id": "67177f1c4da1b9c47eddb380", "points": 6 }
      ]
    },
    {
      "name": "writing",
      "sectionScore": 20,
      "instruction": "Complete two writing tasks within the given time.",
      "duration": 5,
      "questions": [
        { "_id": "671bbc133e42879b0be78624", "points": 10 },
        { "_id": "671bbc133e42879b0be78625", "points": 10 }
      ]
    },
    {
      "name": "general",
      "sectionScore": 10,
      "instruction": "Participate in a recorded spoken interview covering various topics.",
      "duration": 5,
      "questions": [
        { "_id": "671662119e0a1e66671825a0", "points": 5 },
        { "_id": "671662119e0a1e66671825a1", "points": 5 }
      ]
    },
    {
      "name": "grammar",
      "sectionScore": 10,
      "instruction": "Answer questions to demonstrate your understanding of grammar.",
      "duration": 5,
      "questions": [
        { "_id": "671662119e0a1e66671825a2", "points": 5 },
        { "_id": "671662119e0a1e66671825ad", "points": 5 }
      ]
    }
  ],
  "passingScore": 35,
  "totalPossibleScore": 58,
  "difficulty": "elementary",
  "testType": "ielts",
  "isPublished": false,
  "attemptsAllowed": 2,
  "availableFrom": "2023-07-01T00:00:00Z",
  "availableUntil": "2025-12-31T23:59:59Z"
}


#### Get a test
GET {{baseUrl}}/tests/671bbc5d3e42879b0be78638
Authorization: Bearer {{accessToken}}   

#### Get all tests with pagination
GET {{baseUrl}}/tests?page=1&limit=10&orderBy=createdAt&sortBy=desc
Authorization: Bearer {{accessToken}}   

#### Get a test for attempt
GET {{baseUrl}}/tests/671bbc5d3e42879b0be78638/attempt
Authorization: Bearer {{accessToken}}   

