const { MatchingQuestion } = require("../../model/question.model.v1");
const matchingQuestions = [
  {
    type: "matching",
    section: "grammar",
    questionText: "Match the following words to their correct definitions:",
    instruction: "Match each word to its corresponding definition.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Exuberant" },
      { id: 2, text: "Melancholy" },
      { id: 3, text: "Stoic" },
    ],
    rightColumn: [
      { id: "A", text: "Joyfully unrestrained" },
      { id: "B", text: "Sad or depressed" },
      { id: "C", text: "Showing little emotion" },
    ],
    correctPairs: [
      { left: 1, right: "A" },
      { left: 2, right: "B" },
      { left: 3, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match the following words to their synonyms:",
    instruction: "Match each word to its corresponding synonym.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Enormous" },
      { id: 2, text: "Brave" },
      { id: 3, text: "Intelligent" },
    ],
    rightColumn: [
      { id: "A", text: "Huge" },
      { id: "B", text: "Courageous" },
      { id: "C", text: "Smart" },
    ],
    correctPairs: [
      { left: 1, right: "A" },
      { left: 2, right: "B" },
      { left: 3, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "general",
    questionText: "Match the countries to their capitals:",
    instruction: "Match each country to its corresponding capital city.",
    difficulty: 4,
    leftColumn: [
      { id: 1, text: "France" },
      { id: 2, text: "Japan" },
      { id: 3, text: "Brazil" },
    ],
    rightColumn: [
      { id: "A", text: "Tokyo" },
      { id: "B", text: "Paris" },
      { id: "C", text: "Brasília" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "A" },
      { left: 3, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "grammar",
    questionText: "Match the following words to their correct part of speech:",
    instruction: "Match each word to its corresponding part of speech.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Quickly" },
      { id: 2, text: "Happiness" },
      { id: 3, text: "Jumped" },
    ],
    rightColumn: [
      { id: "A", text: "Adverb" },
      { id: "B", text: "Noun" },
      { id: "C", text: "Verb" },
    ],
    correctPairs: [
      { left: 1, right: "A" },
      { left: 2, right: "B" },
      { left: 3, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "general",
    questionText: "Match the inventors to their inventions:",
    instruction: "Match each inventor to their corresponding invention.",
    difficulty: 5,
    leftColumn: [
      { id: 1, text: "Alexander Graham Bell" },
      { id: 2, text: "Thomas Edison" },
      { id: 3, text: "Nikola Tesla" },
      { id: 4, text: "Marie Curie" },
    ],
    rightColumn: [
      { id: "A", text: "Light bulb" },
      { id: "B", text: "Telephone" },
      { id: "C", text: "Alternating current" },
      { id: "D", text: "Radioactivity" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "A" },
      { left: 3, right: "C" },
      { left: 4, right: "D" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match these advanced words to their definitions:",
    instruction: "Match each word to its corresponding definition.",
    difficulty: 5,
    leftColumn: [
      { id: 1, text: "Ephemeral" },
      { id: 2, text: "Sycophant" },
      { id: 3, text: "Ubiquitous" },
      { id: 4, text: "Perfidious" },
    ],
    rightColumn: [
      { id: "A", text: "Existing everywhere" },
      { id: "B", text: "Lasting for a very short time" },
      { id: "C", text: "Deceitful and untrustworthy" },
      {
        id: "D",
        text: "A person who acts obsequiously toward someone important",
      },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "D" },
      { left: 3, right: "A" },
      { left: 4, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "grammar",
    questionText: "Match these complex grammatical terms to their definitions:",
    instruction: "Match each grammatical term to its corresponding definition.",
    difficulty: 5,
    leftColumn: [
      { id: 1, text: "Subjunctive mood" },
      { id: 2, text: "Synecdoche" },
      { id: 3, text: "Anacoluthon" },
      { id: 4, text: "Zeugma" },
    ],
    rightColumn: [
      {
        id: "A",
        text: "A figure of speech in which a part is used to represent the whole",
      },
      {
        id: "B",
        text: "A verb form expressing what is imagined or wished or possible",
      },
      {
        id: "C",
        text: "A sentence or construction in which the expected grammatical sequence is absent",
      },
      {
        id: "D",
        text: "A figure of speech in which a word applies to two others in different senses",
      },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "A" },
      { left: 3, right: "C" },
      { left: 4, right: "D" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match these intermediate words to their definitions:",
    instruction: "Match each word to its corresponding definition.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Ambiguous" },
      { id: 2, text: "Benevolent" },
      { id: 3, text: "Inundate" },
      { id: 4, text: "Paradox" },
    ],
    rightColumn: [
      { id: "A", text: "Well-meaning and kindly" },
      { id: "B", text: "Open to more than one interpretation" },
      { id: "C", text: "A statement that seems contradictory but may be true" },
      { id: "D", text: "Overwhelm with things or people" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "A" },
      { left: 3, right: "D" },
      { left: 4, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match these scientific terms to their definitions:",
    instruction: "Match each term to its corresponding definition.",
    difficulty: 4,
    leftColumn: [
      { id: 1, text: "Osmosis" },
      { id: 2, text: "Photosynthesis" },
      { id: 3, text: "Cellular respiration" },
      { id: 4, text: "Mitosis" },
    ],
    rightColumn: [
      { id: "A", text: "Process by which cells divide" },
      { id: "B", text: "Movement of water across a membrane" },
      { id: "C", text: "Conversion of light energy to chemical energy" },
      { id: "D", text: "Process of energy release from organic compounds" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "C" },
      { left: 3, right: "D" },
      { left: 4, right: "A" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "grammar",
    questionText: "Match the verb tenses to their correct examples:",
    instruction: "Match each verb tense to the correct sentence.",
    difficulty: 4,
    leftColumn: [
      { id: 1, text: "Present Perfect" },
      { id: 2, text: "Past Continuous" },
      { id: 3, text: "Future Simple" },
      { id: 4, text: "Present Continuous" },
    ],
    rightColumn: [
      { id: "A", text: "I will study tomorrow." },
      { id: "B", text: "I have completed the task." },
      { id: "C", text: "I was reading a book." },
      { id: "D", text: "I am watching TV now." },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "C" },
      { left: 3, right: "A" },
      { left: 4, right: "D" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match the following idioms to their meanings:",
    instruction: "Match each idiom to its correct meaning.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Break the ice" },
      { id: 2, text: "Hit the sack" },
      { id: 3, text: "Bite the bullet" },
      { id: 4, text: "Cut corners" },
    ],
    rightColumn: [
      { id: "A", text: "To go to bed" },
      { id: "B", text: "Do something in the easiest way" },
      { id: "C", text: "Do something unpleasant because it is necessary" },
      { id: "D", text: "Start a conversation or interaction" },
    ],
    correctPairs: [
      { left: 1, right: "D" },
      { left: 2, right: "A" },
      { left: 3, right: "C" },
      { left: 4, right: "B" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "grammar",
    questionText: "Match the types of nouns to their examples:",
    instruction: "Match each type of noun to its example.",
    difficulty: 2,
    leftColumn: [
      { id: 1, text: "Proper Noun" },
      { id: 2, text: "Abstract Noun" },
      { id: 3, text: "Common Noun" },
      { id: 4, text: "Collective Noun" },
    ],
    rightColumn: [
      { id: "A", text: "Courage" },
      { id: "B", text: "Team" },
      { id: "C", text: "Table" },
      { id: "D", text: "Paris" },
    ],
    correctPairs: [
      { left: 1, right: "D" },
      { left: 2, right: "A" },
      { left: 3, right: "C" },
      { left: 4, right: "B" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match the following phrasal verbs to their meanings:",
    instruction: "Match each phrasal verb to its corresponding meaning.",
    difficulty: 4,
    leftColumn: [
      { id: 1, text: "Give up" },
      { id: 2, text: "Run into" },
      { id: 3, text: "Look after" },
      { id: 4, text: "Get over" },
    ],
    rightColumn: [
      { id: "A", text: "Take care of" },
      { id: "B", text: "Recover from something" },
      { id: "C", text: "Stop doing something" },
      { id: "D", text: "Meet someone unexpectedly" },
    ],
    correctPairs: [
      { left: 1, right: "C" },
      { left: 2, right: "D" },
      { left: 3, right: "A" },
      { left: 4, right: "B" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "general",
    questionText: "Match these world capitals to their countries:",
    instruction: "Match each capital to its corresponding country.",
    difficulty: 2,
    leftColumn: [
      { id: 1, text: "Tokyo" },
      { id: 2, text: "Paris" },
      { id: 3, text: "Canberra" },
      { id: 4, text: "Ottawa" },
    ],
    rightColumn: [
      { id: "A", text: "Australia" },
      { id: "B", text: "Japan" },
      { id: "C", text: "Canada" },
      { id: "D", text: "France" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "D" },
      { left: 3, right: "A" },
      { left: 4, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "grammar",
    questionText: "Match the sentence structures to their examples:",
    instruction: "Match each sentence structure to the corresponding sentence.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Simple Sentence" },
      { id: 2, text: "Compound Sentence" },
      { id: 3, text: "Complex Sentence" },
      { id: 4, text: "Compound-Complex Sentence" },
    ],
    rightColumn: [
      { id: "A", text: "I went to the store, but it was closed." },
      { id: "B", text: "Because I was late, I missed the meeting." },
      {
        id: "C",
        text: "He reads books and writes articles, but he prefers watching movies.",
      },
      { id: "D", text: "She sings." },
    ],
    correctPairs: [
      { left: 1, right: "D" },
      { left: 2, right: "A" },
      { left: 3, right: "B" },
      { left: 4, right: "C" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match the synonyms to their corresponding words:",
    instruction: "Match each synonym to the correct word.",
    difficulty: 3,
    leftColumn: [
      { id: 1, text: "Brave" },
      { id: 2, text: "Happy" },
      { id: 3, text: "Angry" },
      { id: 4, text: "Smart" },
    ],
    rightColumn: [
      { id: "A", text: "Furious" },
      { id: "B", text: "Courageous" },
      { id: "C", text: "Cheerful" },
      { id: "D", text: "Intelligent" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "C" },
      { left: 3, right: "A" },
      { left: 4, right: "D" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "general",
    questionText: "Match the invention to its inventor:",
    instruction: "Match each invention to its corresponding inventor.",
    difficulty: 4,
    leftColumn: [
      { id: 1, text: "Light bulb" },
      { id: 2, text: "Telephone" },
      { id: 3, text: "Airplane" },
      { id: 4, text: "Theory of relativity" },
    ],
    rightColumn: [
      { id: "A", text: "Albert Einstein" },
      { id: "B", text: "Thomas Edison" },
      { id: "C", text: "Alexander Graham Bell" },
      { id: "D", text: "Wright Brothers" },
    ],
    correctPairs: [
      { left: 1, right: "B" },
      { left: 2, right: "C" },
      { left: 3, right: "D" },
      { left: 4, right: "A" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "matching",
    section: "vocabulary",
    questionText: "Match these business terms to their definitions:",
    instruction: "Match each term to its correct definition.",
    difficulty: 5,
    leftColumn: [
      { id: 1, text: "Liability" },
      { id: 2, text: "Equity" },
      { id: 3, text: "Asset" },
      { id: 4, text: "Revenue" },
    ],
    rightColumn: [
      { id: "A", text: "The total income generated by a company" },
      { id: "B", text: "The value of ownership in a company" },
      { id: "C", text: "Something valuable owned by a company" },
      { id: "D", text: "An obligation or debt" },
    ],
    correctPairs: [
      { left: 1, right: "D" },
      { left: 2, right: "B" },
      { left: 3, right: "C" },
      { left: 4, right: "A" },
    ],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
];

async function seedMatchingQuestions() {
  try {
    const insertedQuestions = await MatchingQuestion.insertMany(
      matchingQuestions
    );
    return insertedQuestions;
  } catch (error) {
    console.error(error);
  }
}

module.exports = { matchingQuestions, seedMatchingQuestions };
