const { MultipleChoiceQuestion } = require("../question.model.v1");

const multipleChoiceQuestions = [
  {
    type: "multiple_choice",
    section: "listening",
    questionText: "Which of the following are examples of figurative language?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Metaphor", "Simile", "Alliteration", "Onomatopoeia"],
    correctAnswers: [true, true, true, true],
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567890",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of these words are synonyms for 'happy'?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Joyful", "Elated", "Gloomy", "Ecstatic"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are Shakespearean plays?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Macbeth", "The Great Gatsby", "Hamlet", "To Kill a Mockingbird"],
    correctAnswers: [true, false, true, false],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "general",
    questionText: "Which of these are examples of non-fiction genres?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Biography", "Science Fiction", "Memoir", "Historical Fiction"],
    correctAnswers: [true, false, true, false],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "general",
    questionText: "Which of the following are examples of literary devices?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Foreshadowing", "Irony", "Punctuation", "Allusion"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText:
      "Which of these words are commonly used as transitional phrases?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["However", "Therefore", "Quickly", "Nevertheless"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "listening",
    questionText: "Which of the following are examples of tone in writing?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Sarcastic", "Blue", "Optimistic", "Tall"],
    correctAnswers: [true, false, true, false],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of these are examples of poetic forms?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Sonnet", "Haiku", "Essay", "Villanelle"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "listening",
    questionText:
      "Which of the following are examples of narrative point of view?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: [
      "First Person",
      "Third Person Limited",
      "Past Tense",
      "Omniscient",
    ],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of these are elements of a story's plot?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Rising Action", "Climax", "Setting", "Resolution"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are literary devices?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Metaphor", "Simile", "Paragraph", "Alliteration"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "listening",
    questionText: "Which of these are types of figurative language?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Personification", "Hyperbole", "Punctuation", "Onomatopoeia"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are parts of speech?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Noun", "Verb", "Sentence", "Adjective"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "general",
    questionText: "Which of these are types of poetry?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Limerick", "Prose", "Ballad", "Free Verse"],
    correctAnswers: [true, false, true, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are examples of text structures?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: [
      "Cause and Effect",
      "Compare and Contrast",
      "Dialogue",
      "Chronological",
    ],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "general",
    questionText: "Which of these are types of conflict in literature?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: [
      "Man vs. Nature",
      "Man vs. Society",
      "Man vs. Punctuation",
      "Man vs. Self",
    ],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are examples of genres?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Mystery", "Science Fiction", "Paragraph", "Romance"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "listening",
    questionText: "Which of these are types of characterization?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Direct", "Indirect", "Alphabetical", "Dynamic"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of the following are examples of rhetorical devices?",
    instruction: "Select all that apply.",
    difficulty: 3,
    answers: ["Ethos", "Pathos", "Logos", "Mythos"],
    correctAnswers: [true, true, true, false],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "multiple_choice",
    section: "reading",
    questionText: "Which of these are elements of a story's setting?",
    instruction: "Select all that apply.",
    difficulty: 2,
    answers: ["Time", "Place", "Characters", "Atmosphere"],
    correctAnswers: [true, true, false, true],
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
];
async function seedMultipleChoiceQuestions() {
  try {
    const result = await MultipleChoiceQuestion.insertMany(
      multipleChoiceQuestions
    );
    return result;
  } catch (error) {
    console.error(error);
  }
}
module.exports = { multipleChoiceQuestions, seedMultipleChoiceQuestions };
