const singleChoiceQuestions = [
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is a synonym for 'happy'?",
    instruction: "Choose the correct answer.",
    difficulty: 1,
    answers: ["Sad", "Joyful", "Angry", "Tired"],
    correctAnswer: "Joyful",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567891",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the past tense of 'eat'?",
    instruction: "Select the correct form.",
    difficulty: 2,
    answers: ["Eated", "Ate", "Eaten", "Eating"],
    correctAnswer: "Ate",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567892",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which of the following is a proper noun?",
    instruction: "Choose the correct option.",
    difficulty: 2,
    answers: ["Dog", "City", "London", "Beautiful"],
    correctAnswer: "London",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567893",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the plural of 'child'?",
    instruction: "Select the correct plural form.",
    difficulty: 2,
    answers: ["Childs", "Children", "Childen", "Childres"],
    correctAnswer: "Children",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567894",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence is grammatically correct?",
    instruction: "Choose the sentence with proper grammar.",
    difficulty: 3,
    answers: [
      "She don't like ice cream.",
      "They was happy about the news.",
      "He doesn't want to go.",
      "We is going to the park.",
    ],
    correctAnswer: "He doesn't want to go.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567895",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the comparative form of 'good'?",
    instruction: "Select the correct comparative form.",
    difficulty: 2,
    answers: ["Gooder", "More good", "Better", "Best"],
    correctAnswer: "Better",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567896",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is a conjunction?",
    instruction: "Choose the word that functions as a conjunction.",
    difficulty: 3,
    answers: ["Quickly", "Because", "Happy", "Jump"],
    correctAnswer: "Because",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567897",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the correct spelling?",
    instruction: "Select the correctly spelled word.",
    difficulty: 2,
    answers: ["Accomodate", "Accommodate", "Acommodate", "Accomoddate"],
    correctAnswer: "Accommodate",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567898",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence uses the correct form of 'there'?",
    instruction: "Choose the sentence with the proper usage.",
    difficulty: 2,
    answers: [
      "Their going to the store.",
      "There going to the store.",
      "They're going to the store.",
      "There're going to the store.",
    ],
    correctAnswer: "They're going to the store.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567899",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the past participle of 'write'?",
    instruction: "Select the correct past participle form.",
    difficulty: 2,
    answers: ["Writed", "Wrote", "Written", "Writing"],
    correctAnswer: "Written",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567900",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is an adverb?",
    instruction: "Choose the word that functions as an adverb.",
    difficulty: 3,
    answers: ["Fast", "Quickly", "Speed", "Rapid"],
    correctAnswer: "Quickly",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567901",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the opposite of 'brave'?",
    instruction: "Select the antonym for 'brave'.",
    difficulty: 1,
    answers: ["Cowardly", "Strong", "Fearless", "Bold"],
    correctAnswer: "Cowardly",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567902",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence is in the passive voice?",
    instruction: "Choose the sentence written in passive voice.",
    difficulty: 3,
    answers: [
      "The cat chased the mouse.",
      "She baked a cake for her birthday.",
      "The book was written by the famous author.",
      "They will announce the winner tomorrow.",
    ],
    correctAnswer: "The book was written by the famous author.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567903",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the correct order of adjectives?",
    instruction: "Select the phrase with the correct adjective order.",
    difficulty: 3,
    answers: [
      "A red big balloon",
      "A big red balloon",
      "A balloon red big",
      "A balloon big red",
    ],
    correctAnswer: "A big red balloon",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567904",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is a preposition?",
    instruction: "Choose the word that functions as a preposition.",
    difficulty: 2,
    answers: ["Happily", "Under", "Sing", "Loud"],
    correctAnswer: "Under",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567905",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the plural of 'phenomenon'?",
    instruction: "Select the correct plural form.",
    difficulty: 3,
    answers: ["Phenomenons", "Phenomenas", "Phenomena", "Phenomenae"],
    correctAnswer: "Phenomena",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567906",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence uses the correct form of 'who/whom'?",
    instruction: "Choose the sentence with proper usage.",
    difficulty: 3,
    answers: [
      "Who did you give the book to?",
      "Whom did you give the book to?",
      "To who did you give the book?",
      "To whom you gave the book?",
    ],
    correctAnswer: "Whom did you give the book to?",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567907",
  },
  {
    type: "single_choice",
    section: "general",
    questionText:
      "What is the correct form of the verb in this sentence: 'Neither of the girls ___ going to the party.'",
    instruction: "Select the proper verb form.",
    difficulty: 3,
    answers: ["Is", "Are", "Were", "Was"],
    correctAnswer: "Is",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567908",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is a gerund?",
    instruction: "Choose the word that functions as a gerund.",
    difficulty: 3,
    answers: ["Quickly", "Fast", "Running", "Run"],
    correctAnswer: "Running",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567909",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the superlative form of 'far'?",
    instruction: "Select the correct superlative form.",
    difficulty: 2,
    answers: ["Farer", "More far", "Farthest", "Farther"],
    correctAnswer: "Farthest",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567910",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence contains a dangling modifier?",
    instruction: "Choose the sentence with a dangling modifier.",
    difficulty: 3,
    answers: [
      "The dog barked loudly at the mailman.",
      "Walking down the street, the trees were beautiful.",
      "She bought a new car after saving money for years.",
      "The children played happily in the park.",
    ],
    correctAnswer: "Walking down the street, the trees were beautiful.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567911",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the correct possessive form of 'women'?",
    instruction: "Select the proper possessive form.",
    difficulty: 2,
    answers: ["Womens'", "Women's", "Womans'", "Woman's"],
    correctAnswer: "Women's",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567912",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which word is an example of onomatopoeia?",
    instruction: "Choose the word that represents a sound.",
    difficulty: 3,
    answers: ["Loud", "Bright", "Buzz", "Soft"],
    correctAnswer: "Buzz",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567913",
  },
  {
    type: "single_choice",
    section: "general",
    questionText:
      "What is the correct form of the verb in this sentence: 'The team ___ practicing every day.'",
    instruction: "Select the proper verb form.",
    difficulty: 2,
    answers: ["Is", "Are", "Were", "Was"],
    correctAnswer: "Is",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567914",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence uses parallelism correctly?",
    instruction: "Choose the sentence with proper parallel structure.",
    difficulty: 3,
    answers: [
      "She likes swimming, to hike, and riding bikes.",
      "She likes swimming, hiking, and biking.",
      "She likes to swim, hiking, and to ride bikes.",
      "She likes to swim, to hike, and riding bikes.",
    ],
    correctAnswer: "She likes swimming, hiking, and biking.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567915",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "What is the correct plural form of 'crisis'?",
    instruction: "Select the proper plural form.",
    difficulty: 3,
    answers: ["Crisises", "Crises", "Crisises", "Crisis"],
    correctAnswer: "Crises",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567916",
  },
  {
    type: "single_choice",
    section: "general",
    questionText: "Which sentence contains a split infinitive?",
    instruction: "Choose the sentence with a split infinitive.",
    difficulty: 3,
    answers: [
      "He wanted to quickly finish his homework.",
      "She decided to go to the store.",
      "They hoped to win the game easily.",
      "We tried to carefully explain the situation.",
    ],
    correctAnswer: "He wanted to quickly finish his homework.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567917",
  },
  {
    type: "single_choice",
    section: "general",
    questionText:
      "What is the correct form of the comparative adjective in this sentence: 'This book is ___ than that one.'",
    instruction: "Select the proper comparative form.",
    difficulty: 2,
    answers: ["More good", "Gooder", "Better", "Best"],
    correctAnswer: "Better",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567918",
  },
  {
    type: "single_choice",
    section: "vocabulary",
    questionText: "Which word is a synonym for 'ubiquitous'?",
    instruction: "Select the word that means the same as 'ubiquitous'.",
    difficulty: 4,
    answers: ["Rare", "Omnipresent", "Unique", "Scarce"],
    correctAnswer: "Omnipresent",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567919",
  },
  {
    type: "single_choice",
    section: "grammar",
    questionText: "Which sentence uses the past perfect tense correctly?",
    instruction:
      "Choose the sentence with the correct use of past perfect tense.",
    difficulty: 3,
    answers: [
      "I had finished my homework before dinner.",
      "I have finished my homework before dinner.",
      "I finished my homework before dinner.",
      "I was finishing my homework before dinner.",
    ],
    correctAnswer: "I had finished my homework before dinner.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567920",
  },
  {
    type: "single_choice",
    section: "vocabulary",
    questionText: "What is the meaning of the word 'ephemeral'?",
    instruction: "Select the definition that best describes 'ephemeral'.",
    difficulty: 4,
    answers: ["Lasting forever", "Short-lived", "Intense", "Transparent"],
    correctAnswer: "Short-lived",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567921",
  },
  {
    type: "single_choice",
    section: "grammar",
    questionText: "Which sentence contains a dangling modifier?",
    instruction: "Choose the sentence with a dangling modifier.",
    difficulty: 4,
    answers: [
      "Walking down the street, the birds were chirping loudly.",
      "The birds were chirping loudly as I walked down the street.",
      "I heard the birds chirping loudly while walking down the street.",
      "Loudly chirping, the birds accompanied my walk down the street.",
    ],
    correctAnswer: "Walking down the street, the birds were chirping loudly.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567922",
  },
  {
    type: "single_choice",
    section: "vocabulary",
    questionText: "Which word is an antonym for 'benevolent'?",
    instruction: "Select the word that means the opposite of 'benevolent'.",
    difficulty: 3,
    answers: ["Kindly", "Generous", "Malevolent", "Charitable"],
    correctAnswer: "Malevolent",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567923",
  },
  {
    type: "single_choice",
    section: "grammar",
    questionText: "Which sentence uses the subjunctive mood correctly?",
    instruction:
      "Choose the sentence that correctly uses the subjunctive mood.",
    difficulty: 4,
    answers: [
      "I wish I was taller.",
      "I wish I were taller.",
      "I wish I am taller.",
      "I wish I will be taller.",
    ],
    correctAnswer: "I wish I were taller.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567924",
  },
  {
    type: "single_choice",
    section: "vocabulary",
    questionText: "What does the idiom 'beat around the bush' mean?",
    instruction:
      "Select the correct meaning of the idiom 'beat around the bush'.",
    difficulty: 3,
    answers: [
      "To win easily",
      "To avoid the main topic",
      "To search thoroughly",
      "To criticize harshly",
    ],
    correctAnswer: "To avoid the main topic",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567925",
  },
  {
    type: "single_choice",
    section: "grammar",
    questionText: "Which sentence uses parallel structure correctly?",
    instruction: "Choose the sentence with correct parallel structure.",
    difficulty: 3,
    answers: [
      "She likes swimming, to hike, and riding bikes.",
      "She likes swimming, hiking, and biking.",
      "She likes to swim, hiking, and to ride bikes.",
      "She likes to swim, to hike, and riding bikes.",
    ],
    correctAnswer: "She likes swimming, hiking, and biking.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567926",
  },
  {
    type: "single_choice",
    section: "vocabulary",
    questionText: "Which word best describes someone who is 'loquacious'?",
    instruction: "Select the characteristic that best matches 'loquacious'.",
    difficulty: 4,
    answers: ["Silent", "Talkative", "Shy", "Angry"],
    correctAnswer: "Talkative",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567927",
  },
  {
    type: "single_choice",
    section: "grammar",
    questionText: "Which sentence uses the correct form of the verb 'lie'?",
    instruction: "Choose the sentence with the correct form of 'lie'.",
    difficulty: 3,
    answers: [
      "He has laid on the beach all day.",
      "He has lain on the beach all day.",
      "He has lied on the beach all day.",
      "He has lay on the beach all day.",
    ],
    correctAnswer: "He has lain on the beach all day.",
    isPublic: true,
    createdBy: "60a3e5b9f5e6a81234567928",
  },
];
const SingleChoiceQuestion = require("../question.model.v1");
async function seedSingleChoiceQuestions() {
  try {
    const result = await SingleChoiceQuestion.insertMany(singleChoiceQuestions);
    return result;
  } catch (error) {
    console.error(error);
  }
}

module.exports = { singleChoiceQuestions, seedSingleChoiceQuestions };
