const trueFalseQuestions = [
  {
    type: "true_false",
    section: "general",
    questionText: "The author's argument is well-supported by the evidence.",
    instruction: "Answer the question based on the provided text.",
    difficulty: 3,
    statement: "The author's argument is well-supported by the evidence.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText:
      "The present perfect tense is used for completed past actions.",
    instruction: "Determine if this grammar rule is true or false.",
    difficulty: 3,
    statement: "The present perfect tense is used for completed past actions.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "vocabulary",
    questionText: "'Ambiguous' and 'vague' have exactly the same meaning.",
    instruction:
      "Evaluate if this statement about word meanings is true or false.",
    difficulty: 4,
    statement: "'Ambiguous' and 'vague' have exactly the same meaning.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText: "All regular verbs end in '-ed' in the past tense.",
    instruction: "Determine if this grammar statement is true or false.",
    difficulty: 2,
    statement: "All regular verbs end in '-ed' in the past tense.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "vocabulary",
    questionText: "The word 'affect' is always used as a verb.",
    instruction:
      "Evaluate if this statement about word usage is true or false.",
    difficulty: 4,
    statement: "The word 'affect' is always used as a verb.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "general",
    questionText:
      "Academic writing should always avoid using the first person.",
    instruction: "Determine if this writing rule is true or false.",
    difficulty: 3,
    statement: "Academic writing should always avoid using the first person.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText: "A semicolon can be used to join two independent clauses.",
    instruction: "Evaluate if this punctuation rule is true or false.",
    difficulty: 4,
    statement: "A semicolon can be used to join two independent clauses.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "vocabulary",
    questionText: "'Infamous' means the same as 'famous'.",
    instruction:
      "Determine if this statement about word meaning is true or false.",
    difficulty: 3,
    statement: "'Infamous' means the same as 'famous'.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "general",
    questionText: "All formal essays must have exactly five paragraphs.",
    instruction: "Evaluate if this writing convention is true or false.",
    difficulty: 3,
    statement: "All formal essays must have exactly five paragraphs.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText:
      "Every sentence must contain a verb to be grammatically correct.",
    instruction: "Determine if this grammar rule is true or false.",
    difficulty: 3,
    statement:
      "Every sentence must contain a verb to be grammatically correct.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "vocabulary",
    questionText: "The prefix 'un-' always means 'not' or 'opposite of'.",
    instruction: "Evaluate if this statement about prefixes is true or false.",
    difficulty: 4,
    statement: "The prefix 'un-' always means 'not' or 'opposite of'.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "general",
    questionText: "Passive voice should never be used in good writing.",
    instruction: "Determine if this writing guideline is true or false.",
    difficulty: 4,
    statement: "Passive voice should never be used in good writing.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText:
      "Articles (a, an, the) are required before all nouns in English.",
    instruction: "Evaluate if this grammar rule is true or false.",
    difficulty: 4,
    statement:
      "Articles (a, an, the) are required before all nouns in English.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "vocabulary",
    questionText: "All words ending in '-ly' are adverbs.",
    instruction:
      "Determine if this statement about word forms is true or false.",
    difficulty: 3,
    statement: "All words ending in '-ly' are adverbs.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "general",
    questionText: "Contractions should never be used in formal writing.",
    instruction: "Evaluate if this writing rule is true or false.",
    difficulty: 2,
    statement: "Contractions should never be used in formal writing.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
  {
    type: "true_false",
    section: "grammar",
    questionText: "The subject and verb must always be adjacent in a sentence.",
    instruction: "Determine if this grammar rule is true or false.",
    difficulty: 4,
    statement: "The subject and verb must always be adjacent in a sentence.",
    isPublic: true,
    createdBy: "66eda220f1577aa9a314ab30",
  },
];
